### ISSUE TITLE
Cannot generate access token: "Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)"

### ISSUE THREAD

**Issue by nicokosi** [mgryszko/stra-token#1] opened 2021-01-26 07:03 UTC
I cannot generate an access token:
```
strava-access-token $STRAVA_CLIENT_ID $STRAVA_CLIENT_SECRET
Open http://localhost:8080/ in browser
/usr/local/lib/ruby/gems/3.0.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1755:in `detect_rack_handler': Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1493:in `run!'
	from /usr/local/bin/strava-access-token:51:in `<main>'
```

For information (not sure if useful 😇):
```shell
ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
```

**Comment by nicokosi** [comment] 2021-01-26 18:03
Error does not occur when using Ruby 2.7:
```
$ rbenv local 2.7.2
$ rbenv version
2.7.2 (set by /Users/nicolas/work/strava-access-token/.ruby-version)
$ rbenv exec ruby strava-access-token $STRAVA_CLIENT_ID $STRAVA_CLIENT_SECRET
Open http://localhost:8080/ in browser
[2021-01-26 19:01:28] INFO  WEBrick 1.6.0
[2021-01-26 19:01:28] INFO  ruby 2.7.2 (2020-10-01) [x86_64-darwin19]
== Sinatra (v2.1.0) has taken the stage on 8080 for development with backup from WEBrick
[2021-01-26 19:01:28] INFO  WEBrick::HTTPServer#start: pid=69723 port=8080
```

**Comment by mgryszko** [comment] 2021-01-27 18:53
Hi @nicokosi, thanks for checking that this tiny tool is still working. I understand that the issue is solved - I merged your documentation update.

**Closed as completed by mgryszko** 2021-01-27 18:53 UTC

**Comment by nicokosi** [comment] 2021-01-28 07:42
> Hi @nicokosi, thanks for checking that this tiny tool is still working. I understand that the issue is solved - I merged your documentation update.

Hi @mgryszko, thanks. 👍
For information, I use `strava-access-token` for my own tiny tool (toy project): https://github.com/nicokosi/strava-activity-graphs#usage. ❤️
